# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rmQ_h1H-OAG22TXHT1BHJvUfvndjIVq
"""



#2.1.5 LAB Working with the print() function
print("Hello, python!")
print("Riyan")
print("ze do caixão")
print("tremonti")
print("aoba" , end=" ")
print("tchubiraudaudau\ntchubiraudaudau")
print("tchubiraudaudau" , "tchubiraudaudau" , sep="--")
print("não sei o que" , "nao sei o que la" , "isso e aquilo")

print("Programming","Essentials","in",sep="***" , end="...")
print("Python")
print('\'Greg\'s book.\'')

#2.2.1 Literals – the data in itself
print(1+2+3)
print("1+2+3")
print(6.62607E-34)



